### ISSUE TITLE
Error 2168-0002 when launching Xash (9.0.0)

### ISSUE THREAD

**Issue by WORMSTweaker** [switchports/xash3d-switch#10]
Hello,
I wanted to try out Xash, but apparently I'm not allowed to eh?...

Anyway, each time I try to launch Xash from the HBL, I get a hard crash, with the error code 2168-0002 ("Userland ARM data abort. Also caused by abnormal process termination via svcExitProcess. Note: directly jumping to nnMain()-retaddr from non-main-thread has the same result.", taken from the[ Switchbrew wiki](https://switchbrew.org/w/index.php?title=Error_codes&mobileaction=toggle_view_desktop#Fatal_Errors) )
I do not know if this is related to Xash exclusively, or if my setup is at fault, so I'm just reporting this error in hope that somebody can help me. I've also including this dump log from Atmosphère, for good measure.
[01568815208_010000000000100d.log](https://github.com/switchports/xash3d-switch/files/3626931/01568815208_010000000000100d.log)

My Xash3D folder does exist on my card, with a fresh valve folder in it, I'm running Hekate 5.0.2, with Atmosphère 9.4.0, HOS version 9.0.0, in a emuMMC

**Comment by Datamats** [comment]
If you're able you should try to launch the xash3d valve nro thorugh nxlink to get the logs, it might tell you where the issue is

**Comment by WORMSTweaker** [comment]
Okay so
I already tried to launch it without using an applet, doesn't work too, I just got an HOS error screen (Software closed because of an error)
nxlink logs indicate that apparently Xash cannot change to its directory
`[18:33:43]  Changing working directory to sdmc:/xash3d failed.
======================================
Xash Error: Changing working directory to sdmc:/xash3d failed.

======================================
[18:33:43]  Switch: Switching clock speed to 1020000000
exiting ...`
