### ISSUE TITLE
SDL2 preemptive multithreading 

### ISSUE THREAD

**Issue by Cpasjuste** [switchports/xash3d-switch#4]
Hi @Datamats, i just implemented preemptive multithreading in SDL2, would it be possible for you to test it to see if there is no issues with it (mainly audio) before pushing it to pacman packages?

Thanks.

[libSDL2.zip](https://github.com/switchports/xash3d-switch/files/2603664/libSDL2.zip)

**Comment by Cpasjuste** [comment]
Thanks :) (nothing urgent btw).

**Comment by Datamats** [comment]
Seems to behave fine for me and it's not breaking anything

**Comment by Cpasjuste** [comment]
Thanks for the testing @Datamats ! I'll do more testing on my side and will push the changes to devkit pacman packages if all goes well. Again, thanks for your time.

**Comment by Datamats** [comment]
I'll close this because since it seems like it has been merged into the dkp SDL2 port
