### ISSUE TITLE
Gunman Chronicles Goldsrc

### ISSUE THREAD

**Issue by Magnif1cus** [switchports/xash3d-switch#9]
Hi, can I play Gunman Chronicles in my switch?? It's the same engine as half life (Goldsrc), that game was awesome ages ago.

**Comment by Datamats** [comment]
If it contains custom entities or other custom code, the answer is no.

**Comment by Magnif1cus** [comment]
OMG I have tried it, its working!!!

**Comment by Magnif1cus** [comment]
This game is working on pc under Xash3D Engine.

I have tried on nintendo switch and:
Menu is working good and the game starts, but have some bugs and cant play normally some of the ia npcs are invisible.
Multiplayer starts normally too and weapons works.

Could you add support for this game on nintendo switch in a future?

**Comment by Datamats** [comment]
This is due to the game requiring a proprietary dll that will only work on PC. There is nothing that can be done about that, it will never be supported and cannot be ported.
